version: '3.9'

services:
  lb:
    image: haproxy
    ports:
      - 8000:80
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - server1
      - server2
      - server3
  server1:
    image: myifchat
    environment:
      - SERV_ID=11111
    restart: on-failure
  server2:
    image: myifchat
    environment:
      - SERV_ID=22222
    restart: on-failure
  server3:
    image: myifchat
    environment:
      - SERV_ID=33333
    restart: on-failure
  rds:
    image: redis
    